### ISSUE TITLE
Performant indexOf?

### ISSUE THREAD

**Issue by atifsyedali** [qwertie/btree-typescript#13]
Is there a way we can do `btree.indexOf(key)` in O(log(n)) instead of O(n) in the implementation? Currently I am just doing a forEach and counting.

Similarly, it would be awesome if the set and remove methods returned the position of the inserted or removed entries respectively instead of boolean. This would save a round trip to indexOf.

**Comment by qwertie** [comment]
`BTree` doesn't have `indexOf` because it doesn't have indexes. (Interestingly I _did_ create a [data structure similar to B+tree in C# that _does_ have indexes](http://core.loyc.net/collections/alists-part2) and fast `IndexOf`, but I guess that doesn't help you.)

Normally people look up things in a B+tree by key (`btree.get(key)`). Does this not work for you?

**Comment by qwertie** [comment]
Closed due to inactivity.

**Comment by brurucy** [comment]
@atifsyedali Here, in O(1) time, written both in Typescript: https://github.com/brurucy/n6idus and Rust: https://github.com/brurucy/indexset
