### ISSUE TITLE
Set interfaces are not implemented

### ISSUE THREAD

**Issue by cairomassimo** [qwertie/btree-typescript#14]
Since `BTree` is optimized for implementing sets efficiently, I expected `BTree<K, V>` to implement the `ISortedSet<K>` interface as well.

If used as follows (which I expect to be the standard):
```
const myMap: IMap<K, V> = new BTree();
const mySortedMap: ISortedMap<K, V> = new BTree();
const mySet: ISet<K> = new BTree();
const mySortedSet: ISet<K> = new BTree();
```
the extra methods would not be exposed unless necessary.

I can work on it and open a PR to fix it, if there are no downsides.

Thanks for the nice project! :heart:

**Comment by cairomassimo** [comment]
It appears that the following is sufficient:

```typescript
import BTree, { ISortedSet, ISortedSetF } from 'sorted-btree';

export class BTreeSet<K> extends BTree<K, undefined> implements ISortedSet<K>, ISortedSetF<K> {
  add(key: K) {
    this.set(key, undefined);
  }
}
```

TBH, a `Map` is "more similar" to a collection of its values, not its keys (e.g., the `forEach` method passes the value as first argument, exactly like arrays), so it is a bit strange that `add` accepts a key, not a value.
Nonetheless, there is no ambiguity here since there is no way to just "add" a value to a Map, without specifying a key, reason why I think the `add` method could be safely added to `BTree`.

I see that we have an issue of typing here (if we add `undefined`, we break the guarantee that values have type `V` if `undefined` is not assignable to `V`), so a valid alternative is to use the `BTreeSet` class exactly as defined above.

Thanks.

**Comment by qwertie** [comment]
In fact it is not necessary to define that extra `add` method, it's [already on the prototype](https://github.com/qwertie/btree-typescript/blob/master/b%2Btree.ts#L801) as an alias for `set`. Just cast `BTree<K>` to `ISet<K>` and it should work.

It's been awhile since I wrote `BTree`, but before even reading your whole message I figured the reason that `BTree<K,V>`  doesn't include `add` in its official type definition is because in general it's unsound. As you mentioned, `undefined` is not necessarily assignable to `V`. TypeScript is pretty sophisticated though, maybe there's a way to define an `asSet(): ISortedSet<K>` method such that TypeScript _gives you an error message_ if undefined is not assignable to V...

**Comment by qwertie** [comment]
Oh, and sorry it took so long to get back to you. I haven't worked out how to tell GMail to put GitHub messages directed at me into my "primary" inbox...

**Comment by cairomassimo** [comment]
> In fact it is not necessary to define that extra `add` method, it's [already on the prototype](https://github.com/qwertie/btree-typescript/blob/master/b%2Btree.ts#L801) as an alias for `set`. Just cast `BTree<K>` to `ISet<K>` and it should work.
> 
> It's been awhile since I wrote `BTree`, but before even reading your whole message I figured the reason that `BTree<K,V>` doesn't include `add` in its official type definition is because in general it's unsound. As you mentioned, `undefined` is not necessarily assignable to `V`. TypeScript is pretty sophisticated though, maybe there's a way to define an `asSet(): ISortedSet<K>` method such that TypeScript _gives you an error message_ if undefined is not assignable to V...

I see, that's an amazing idea. I think the correct typing is:
```typescript
asSet(): V extends undefined ? ISet<K> : unknown { /* ... */ }
```

Noticed I used `unknown` instead of `never` because `never` would be assignable to everything.

I wonder if we can avoid it at all, say:
```typescript
type IMapAsSet<K, V> =  V extends undefined ? ISet<K> : unknown;

class BTree<K, V> implements IMap<K, V>, IMapAsSet<K, V> {
  /* ... */
}
```

**Comment by cairomassimo** [comment]
> I wonder if we can avoid it at all, say:
> 
> ```ts
> type IMapAsSet<K, V> =  V extends undefined ? ISet<K> : unknown;
> 
> class BTree<K, V> implements IMap<K, V>, IMapAsSet<K, V> {
>   /* ... */
> }
> ```

Nope:
> A class can only implement an object type or intersection of object types with statically known members. ts(2422)

**Comment by qwertie** [comment]
This apparently doesn't work correctly due to some kind of bug, or strange rule, in TypeScript.

I'm pretty sure the correct* signature is 

    get asSet(): undefined extends V ? ISet<K> : unknown;

(* actually it should return `ISortedSet<K>`, but let's pretend it's `ISet<K>` for awhile)

But `new BTree<A, B>().asSet` seemingly _always_ returns `ISet<A>`. This odd behavior is somewhat specific to `undefined`; if I instead write 

    get asSet(): 'x' extends V ? ISet<K> : unknown;

Then `new BTree<any, string>().asSet` and `new BTree<any, 'x'>().asSet` are both `ISet<any>` as expected, while `new BTree<any, 'nope'>().asSet` and `new BTree<any, null>().asSet` are `unknown` as expected... **however**, `new BTree<any, {}>().asSet` is incorrectly typed as `ISet<any>`. Further investigation shows other anomalies... so I guess TypeScript is just broken?

I'm pushing it out anyway: version 1.7.0.

**Comment by qwertie** [comment]
Oops... amazingly enough, adding an `asSet` property is a breaking change, because (for example) previously `BTree<number, string>` was implicitly convertible to `BTree<number, string|number>`, but the new property somehow causes TypeScript to disallow the conversion while complaining that "Types of property 'diffAgainst' are incompatible." Yeah... sometimes I think TypeScript has a lot of bugs.

So instead, `asSet` will be a standalone function.
