### ISSUE TITLE
nextLowerPair always returns undefined for key of 0

### ISSUE THREAD

**Issue by Thakugan** [qwertie/btree-typescript#9]
This seems to be an issue with 0 being falsy. I haven't tested on any of the other variants.

**Comment by qwertie** [comment]
Confirmed: there is a bug when 0 is passed to nextLowerPair. You were right, it is an issue with 0 being falsy, but the bug is that nextLowerPair(0) returns the second-highest item; it will return `undefined` only if the collection contains fewer than two items. This is related to a second bug, as it was intended that `nextLowerPair(undefined)` would return the highest item, but it returns the second-highest item instead ('luckily' this feature was undocumented).

The bug is fixed and published as v1.2.4, and I've added basic unit tests of `nextLowerPair` and `nextHigherPair`.
